
<!-- Navbar/Menu -->

<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="index.php">Læringsportfolio</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
 </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item ml-auto">
          <a class="nav-link active" aria-current="page" href="index.php">HJEM</a>
        </li>
        <li class="nav-item dropdown ml-auto">
          <a class="nav-link dropdown-toggle" href="design.php" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            DESGIN
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="#">Illustrator</a></li>
            <li><a class="dropdown-item" href="#">Photoshop</a></li>
            <li><a class="dropdown-item" href="#">Farver</a></li>
            <li><a class="dropdown-item" href="#">Typografi</a></li>
            <li><a class="dropdown-item" href="#">Quick'n dirty video</a></li>
            <li><a class="dropdown-item" href="#">Gestaltlovene</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown ml-auto">
          <a class="nav-link dropdown-toggle" href="kodning.php" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            KODNING
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="#">HTML</a></li>
            <li><a class="dropdown-item" href="#">CSS</a></li>
            <li><a class="dropdown-item" href="#">Internettet</a></li>
            <li><a class="dropdown-item" href="#">Responsiv Design</a></li>
            <li><a class="dropdown-item" href="#">Versionsstyring</a></li>
            <li><a class="dropdown-item" href="#">HTML og CSS workshop</a></li>
            <li><a class="dropdown-item" href="#">PHP og serverside</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown ml-auto">
          <a class="nav-link dropdown-toggle" href="kommunikation.php" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            KOMMUNIKATION
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="#">Grundlæggende</a></li>
            <li><a class="dropdown-item" href="#">Kvalitativ og kvantitativ</a></li>
            <li><a class="dropdown-item" href="#">Præsentationsteknik</a></li>
            <li><a class="dropdown-item" href="#">Usabillity</a></li>
            <li><a class="dropdown-item" href="#">Tekstproduktion</a></li>
            <li><a class="dropdown-item" href="#">Paradigmer</a></li>
            <li><a class="dropdown-item" href="#">Ophavsret og licens</a></li>
            <li><a class="dropdown-item" href="#">BMC</a></li>
            <li><a class="dropdown-item" href="#">Informationsarkitektur</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown ml-auto">
          <a class="nav-link dropdown-toggle" href="projekter.php" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PROJEKTER
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="#">Hackathon</a></li>
            <li><a class="dropdown-item" href="#">Design thinking</a></li>
            <li><a class="dropdown-item" href="#">Onepage</a></li>
            <li><a class="dropdown-item" href="#">Portfolio</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
